/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import data.GestorEntidades;
import model.ColaboradorExterno;
import model.GuiaTuristico;
import model.RutaGastronomica;
import model.Vehiculo;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ASUS TUF
 */
public class Main extends javax.swing.JFrame {

     /** Objeto encargado de guardar y mostrar los usuarios del sistema. */
    private GestorEntidades gestorEntidades;

    public Main() {
        initComponents();
        CardLayout cl = (CardLayout) panelContenedor.getLayout();
        cl.show(panelContenedor, "card6");
        panelEventos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER,45,10)); 
        gestorEntidades = new GestorEntidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelContenedor = new javax.swing.JPanel();
        vacio = new javax.swing.JPanel();
        panelColaborador = new javax.swing.JPanel();
        lblNombreColaborador = new javax.swing.JLabel();
        txtNombreColaborador = new javax.swing.JTextField();
        lblRutColaborador = new javax.swing.JLabel();
        txtRutColaborador = new javax.swing.JTextField();
        lblTelefonoColaborador = new javax.swing.JLabel();
        txtTelefonoColaborador = new javax.swing.JTextField();
        lblEspecialidad = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JTextField();
        lblCertificaciones = new javax.swing.JLabel();
        txtCertificaciones = new javax.swing.JTextField();
        panelGuia = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtRutGuia = new javax.swing.JTextField();
        txtTelefonoGuia = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        txtTipoTour = new javax.swing.JTextField();
        txtNombreGuia = new javax.swing.JTextField();
        panelVehiculo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtPatente = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        panelRuta = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNombreRuta = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtParadas = new javax.swing.JTextField();
        panelEventos = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelRegistros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel10.setText("Agencia de turismo LlanquihueTour");

        jLabel1.setText("Tipo de registro:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Colaborador Externo", "Guía Turístico", "Vehículo", "Ruta Gastronómica" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        panelContenedor.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout vacioLayout = new javax.swing.GroupLayout(vacio);
        vacio.setLayout(vacioLayout);
        vacioLayout.setHorizontalGroup(
            vacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 988, Short.MAX_VALUE)
        );
        vacioLayout.setVerticalGroup(
            vacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        panelContenedor.add(vacio, "card6");

        panelColaborador.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Colaborador Externo"));

        lblNombreColaborador.setText("Nombre:");

        txtNombreColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreColaboradorActionPerformed(evt);
            }
        });

        lblRutColaborador.setText("RUT: ");

        txtRutColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutColaboradorActionPerformed(evt);
            }
        });

        lblTelefonoColaborador.setText("Teléfono:");

        lblEspecialidad.setText("Especialidad:");

        lblCertificaciones.setText("Certificaciones:");

        txtCertificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelColaboradorLayout = new javax.swing.GroupLayout(panelColaborador);
        panelColaborador.setLayout(panelColaboradorLayout);
        panelColaboradorLayout.setHorizontalGroup(
            panelColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColaboradorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColaboradorLayout.createSequentialGroup()
                        .addComponent(lblNombreColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRutColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRutColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblTelefonoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefonoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelColaboradorLayout.createSequentialGroup()
                        .addComponent(lblEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCertificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCertificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelColaboradorLayout.setVerticalGroup(
            panelColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColaboradorLayout.createSequentialGroup()
                .addGroup(panelColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRutColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRutColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCertificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCertificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContenedor.add(panelColaborador, "card2");

        panelGuia.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Guía Turístico"));
        panelGuia.setPreferredSize(new java.awt.Dimension(836, 122));

        jLabel4.setText("Nombre:");

        jLabel11.setText("RUT: ");

        jLabel12.setText("Teléfono:");

        jLabel15.setText("Idioma:");

        jLabel16.setText("Tipo de Tour:");

        txtRutGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutGuiaActionPerformed(evt);
            }
        });

        txtTelefonoGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoGuiaActionPerformed(evt);
            }
        });

        txtTipoTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoTourActionPerformed(evt);
            }
        });

        txtNombreGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreGuiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGuiaLayout = new javax.swing.GroupLayout(panelGuia);
        panelGuia.setLayout(panelGuiaLayout);
        panelGuiaLayout.setHorizontalGroup(
            panelGuiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGuiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGuiaLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGuiaLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelGuiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGuiaLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRutGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(txtTelefonoGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGuiaLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoTour, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGuiaLayout.setVerticalGroup(
            panelGuiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuiaLayout.createSequentialGroup()
                .addGroup(panelGuiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGuiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGuiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGuiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTipoTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContenedor.add(panelGuia, "card3");

        panelVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Vehiculo"));

        jLabel8.setText("Capacidad de personas:");

        jLabel13.setText("Tipo de Vehículo:");

        jLabel14.setText("Costo:");

        jLabel17.setText("Estado:");

        jLabel18.setText("Patente:");

        jLabel19.setText("Modelo:");

        jLabel20.setText("Marca:");

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        txtCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadActionPerformed(evt);
            }
        });

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Van", "SUV/4X4", "Bus", "Camioneta" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Usado", "Seminuevo", "En mantención" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVehiculoLayout = new javax.swing.GroupLayout(panelVehiculo);
        panelVehiculo.setLayout(panelVehiculoLayout);
        panelVehiculoLayout.setHorizontalGroup(
            panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelVehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        panelVehiculoLayout.setVerticalGroup(
            panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelContenedor.add(panelVehiculo, "card4");

        panelRuta.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Ruta Gastronómica"));

        jLabel21.setText("Nombre:");

        jLabel22.setText("Duracion (horas):");

        txtNombreRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRutaActionPerformed(evt);
            }
        });

        jLabel23.setText("N° de paradas:");

        javax.swing.GroupLayout panelRutaLayout = new javax.swing.GroupLayout(panelRuta);
        panelRuta.setLayout(panelRutaLayout);
        panelRutaLayout.setHorizontalGroup(
            panelRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutaLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtParadas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        panelRutaLayout.setVerticalGroup(
            panelRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtNombreRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtParadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        panelContenedor.add(panelRuta, "card5");

        panelEventos.setPreferredSize(new java.awt.Dimension(140, 18));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(118, 23));
        btnGuardar.setMinimumSize(new java.awt.Dimension(118, 23));
        btnGuardar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelEventos.add(btnGuardar);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Mostrar registros");
        jButton2.setPreferredSize(new java.awt.Dimension(140, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelEventos.add(jButton2);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.setPreferredSize(new java.awt.Dimension(140, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelEventos.add(jButton3);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Salir");
        jButton4.setPreferredSize(new java.awt.Dimension(140, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelEventos.add(jButton4);

        panelRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros"));

        resultado.setEditable(false);
        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        javax.swing.GroupLayout panelRegistrosLayout = new javax.swing.GroupLayout(panelRegistros);
        panelRegistros.setLayout(panelRegistrosLayout);
        panelRegistrosLayout.setHorizontalGroup(
            panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelRegistrosLayout.setVerticalGroup(
            panelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) panelContenedor.getLayout();
        String seleccion = (String) jComboBox1.getSelectedItem();
        
       
        switch(seleccion){
            case "Seleccione":
                cl.show(panelContenedor, "card6");
                break;
            case "Colaborador Externo":
                cl.show(panelContenedor, "card2");
                break;
            case "Guía Turístico":
                cl.show(panelContenedor, "card3");
                break;
            case "Vehículo":
                cl.show(panelContenedor, "card4");
                break;
            case "Ruta Gastronómica":
                cl.show(panelContenedor, "card5");
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtRutColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutColaboradorActionPerformed

    private void txtNombreColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreColaboradorActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        CardLayout cl = (CardLayout) panelContenedor.getLayout();
        String seleccion = (String) jComboBox1.getSelectedItem();
        
        if(validarCampos()){        
            switch(seleccion){                
                case "Colaborador Externo":
                    String nombreColaborador = txtNombreColaborador.getText().trim();                
                    String rutColaborador = txtRutColaborador.getText().trim();
                    int tlfnColaborador = Integer.parseInt(txtTelefonoColaborador.getText().trim());
                    String especialidad = txtEspecialidad.getText().trim();
                    String certificaciones = txtCertificaciones.getText().trim();

                    ColaboradorExterno colaborador = new ColaboradorExterno(
                          especialidad,
                          certificaciones,
                          nombreColaborador,
                          rutColaborador,
                          tlfnColaborador                          
                  );

                  gestorEntidades.agregarRegistro(colaborador);
                  JOptionPane.showMessageDialog(this,"Colaborador agregado correctamente.");
                    break;
                case "Guía Turístico":
                    String nombreGuia = txtNombreGuia.getText().trim();
                    String rutGuia = txtRutGuia.getText().trim();
                    int tlfnGuia = Integer.parseInt(txtTelefonoGuia.getText().trim());
                    String idioma = txtIdioma.getText().trim();
                    String tour = txtTipoTour.getText().trim();
                    
                    GuiaTuristico guia = new GuiaTuristico(
                          idioma,
                          tour,
                          nombreGuia,
                          rutGuia,
                          tlfnGuia                          
                  );

                  gestorEntidades.agregarRegistro(guia);
                  JOptionPane.showMessageDialog(this,"Guía Turístico agregado correctamente.");
                    break;
                case "Vehículo":
                    String estado = cmbEstado.getSelectedItem().toString();
                    String tipo = cmbTipo.getSelectedItem().toString();
                    int capacidad = Integer.parseInt(txtCapacidad.getText().trim());
                    String marca = txtMarca.getText().trim();
                    String modelo = txtModelo.getText().trim();
                    String patente = txtPatente.getText().trim();
                    int costo = Integer.parseInt(txtCosto.getText().trim());

                    Vehiculo transporte = new Vehiculo(
                          marca,
                          patente,
                          modelo,
                          capacidad,
                          tipo,
                          costo,  
                          estado
                  );

                  gestorEntidades.agregarRegistro(transporte);
                  JOptionPane.showMessageDialog(this,"Vehículo agregado correctamente.");
                    break;
                case "Ruta Gastronómica":
                    int duracion = Integer.parseInt(txtDuracion.getText().trim());
                    String nombreRuta = txtNombreRuta.getText().trim();
                    int paradas = Integer.parseInt(txtParadas.getText().trim());

                    RutaGastronomica ruta = new RutaGastronomica(
                          paradas,
                          nombreRuta,
                          duracion
                  );

                  gestorEntidades.agregarRegistro(ruta);
                  JOptionPane.showMessageDialog(this,"Ruta Gastronómica agregada correctamente.");
                    break;
            }
        }
        limpiarCampos();        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
            this,
            "Desea salir del sistema?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION
    );
    
        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCertificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificacionesActionPerformed

    private void txtTipoTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoTourActionPerformed

    private void txtTelefonoGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoGuiaActionPerformed

    private void txtNombreGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGuiaActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void txtNombreRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreRutaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         limpiarCampos();
        resultado.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String resumen = gestorEntidades.obtenerResumenRegistros();    
        resultado.setText(resumen);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtRutGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutGuiaActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

        private void limpiarCampos() {
            CardLayout cl = (CardLayout) panelContenedor.getLayout();
            String seleccion = (String) jComboBox1.getSelectedItem();
            switch(seleccion){
                case "Colaborador Externo":
                    txtNombreColaborador.setText("");                
                    txtRutColaborador.setText("");
                    txtTelefonoColaborador.setText("");
                    txtEspecialidad.setText("");
                    txtCertificaciones.setText("");
                    break;
                case "Guía Turístico":
                    txtNombreGuia.setText("");
                    txtRutGuia.setText("");
                    txtTelefonoGuia.setText("");
                    txtIdioma.setText("");
                    txtTipoTour.setText("");
                    break;
                case "Vehículo":
                    cmbEstado.setSelectedIndex(0);
                    cmbTipo.setSelectedIndex(0);
                    txtCapacidad.setText("");
                    txtMarca.setText("");
                    txtModelo.setText("");
                    txtPatente.setText("");
                    txtCosto.setText("");
                    break;
                case "Ruta Gastronómica":
                    txtDuracion.setText("");
                    txtNombreRuta.setText("");
                    txtParadas.setText("");
                    break;
            }       
        }
        
        private boolean validarCampos(){
            CardLayout cl = (CardLayout) panelContenedor.getLayout();
            String seleccion = (String) jComboBox1.getSelectedItem();

                switch(seleccion){                
                    case "Colaborador Externo":
                        String nombreColaborador = txtNombreColaborador.getText().trim();                
                        String rutColaborador = txtRutColaborador.getText().trim();
                        String tlfnColaborador = txtTelefonoColaborador.getText().trim();
                        String especialidad = txtEspecialidad.getText().trim();
                        String certificaciones = txtCertificaciones.getText().trim();

                        if (nombreColaborador.equals("") || rutColaborador.equals("") || tlfnColaborador.equals("")||especialidad.equals("") || certificaciones.equals("") ) {
                            JOptionPane.showMessageDialog(
                                    this,
                                    "Debe completar todos los campos."
                            );
                            return false;
                        }
                        break;
                    case "Guía Turístico":
                        String nombreGuia = txtNombreGuia.getText().trim();
                        String rutGuia = txtRutGuia.getText().trim();
                        String tlfnGuia = txtTelefonoGuia.getText().trim();
                        String idioma = txtIdioma.getText().trim();
                        String tour = txtTipoTour.getText().trim();

                        if (nombreGuia.equals("") || rutGuia.equals("") || tlfnGuia.equals("") ||idioma.equals("") || tour.equals("") ) {
                            JOptionPane.showMessageDialog(
                                    this,
                                    "Debe completar todos los campos."
                            );
                            return false;
                        }
                        break;
                    case "Vehículo":
                        String estado = cmbEstado.getSelectedItem().toString();
                        String tipo = cmbTipo.getSelectedItem().toString();
                        String capacidad = txtCapacidad.getText().trim();
                        String marca = txtMarca.getText().trim();
                        String modelo = txtModelo.getText().trim();
                        String patente = txtPatente.getText().trim();
                        String costo = txtCosto.getText().trim();

                        if (estado.equals("") || tipo.equals("") || capacidad.equals("")||marca.equals("") || modelo.equals("") || patente.equals("") || costo.equals("") ) {
                            JOptionPane.showMessageDialog(
                                    this,
                                    "Debe completar todos los campos."
                            );
                            return false;
                        }
                        break;
                    case "Ruta Gastronómica":
                        String duracion = txtDuracion.getText().trim();
                        String nombreRuta = txtNombreRuta.getText().trim();
                        String paradas = txtParadas.getText().trim();

                        if (nombreRuta.equals("") || duracion.equals("") || paradas.equals("") ) {
                            JOptionPane.showMessageDialog(
                                    this,
                                    "Debe completar todos los campos."
                            );
                            return false;
                        }
                        break;
            }
                return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCertificaciones;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblNombreColaborador;
    private javax.swing.JLabel lblRutColaborador;
    private javax.swing.JLabel lblTelefonoColaborador;
    private javax.swing.JPanel panelColaborador;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelEventos;
    private javax.swing.JPanel panelGuia;
    private javax.swing.JPanel panelRegistros;
    private javax.swing.JPanel panelRuta;
    private javax.swing.JPanel panelVehiculo;
    private javax.swing.JTextArea resultado;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtCertificaciones;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombreColaborador;
    private javax.swing.JTextField txtNombreGuia;
    private javax.swing.JTextField txtNombreRuta;
    private javax.swing.JTextField txtParadas;
    private javax.swing.JTextField txtPatente;
    private javax.swing.JTextField txtRutColaborador;
    private javax.swing.JTextField txtRutGuia;
    private javax.swing.JTextField txtTelefonoColaborador;
    private javax.swing.JTextField txtTelefonoGuia;
    private javax.swing.JTextField txtTipoTour;
    private javax.swing.JPanel vacio;
    // End of variables declaration//GEN-END:variables
}
